version: '3'

services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my-network


  perl-app:
    build:
      context: .
      dockerfile: Dockerfile.perl
    ports:
      - "3001:3000"
    networks:
      - my-network
    depends_on:
      - mysql
    volumes:
      - ./perl_app:/perl_app

  vue-app:
    build:
      context: .
      dockerfile: Dockerfile.vue
    networks:
      - my-network
    ports:
      - "5173:5173"
    depends_on:
      - mysql
    volumes:
      - ./vue-app:/vue-app/vue-app

  helloworld:
    build:
      context: .
      dockerfile: Dockerfile.init
    environment:
      - MYSQL_URL=http://localhost
      - MYSQL_PORT=3307
      - BACKEND_URL=http://localhost
      - BACKEND_PORT=3001
      - FRONTEND_URL=http://localhost
      - FRONTEND_PORT=5173

volumes:
  mysql-data:

networks:
  my-network:
