version: '3'

services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my-network

  perl-app:
    build:
      context: .
      dockerfile: Dockerfile.perl
    ports:
      - "3000:3000"
    depends_on:
      - mysql

  # flask:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.flask
  #   networks:
  #     - my-network    
  #   depends_on:
  #   - mysql
  #   ports:
  #     - "5050:5050"
  #   volumes:
  #     - ./flask:/app

  vue-app:
    build:
      context: .
      dockerfile: Dockerfile.vue
    ports:
      - "5173:5173"
    networks:
      - my-network
    depends_on:
      - mysql
    volumes:
      - ./vue-app:/vue-app/vue-app


volumes:
  mysql-data:

networks:
  my-network:
