version: '3'

services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my-network

  perl-app:
    build:
      context: .
      dockerfile: Dockerfile.perl
    ports:
      - "3001:3000"
    networks:
      - my-network
    depends_on:
      - mysql
    volumes:
      - ./perl_app:/perl_app


  react-app:
    build:
      context: .
      dockerfile: Dockerfile.react
    ports:
      - "5175:5173"
    networks:
      - my-network
    depends_on:
      - mysql
    volumes:
      - ./react-app:/react-app/react-app

volumes:
  mysql-data:

networks:
  my-network:
