FROM mysql:8.2

# Environment variables for MySQL
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=tree
ENV MYSQL_USER=leo
ENV MYSQL_PASSWORD=root

# Copy the SQL script to initialize the database schema
COPY ./db/init.sql /docker-entrypoint-initdb.d/

EXPOSE 3306
