FROM mysql:5.7

# Environment variables for MySQL
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=tree
ENV MYSQL_USER=leo
ENV MYSQL_PASSWORD=root

# Copy the SQL script to initialize the database schema
COPY ./db/init.sql /docker-entrypoint-initdb.d/

# Additional configuration or customizations can be added here if needed
