version: '3'

services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    container_name: mysql-container
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my-network

  flask:
    build:
      context: .
      dockerfile: Dockerfile.flask
    container_name: flask
    networks:
      - my-network    
    depends_on:
    - mysql
    ports:
      - "5050:5050"
    volumes:
      - ./flask:/app

  react-app:
    build:
      context: .
      dockerfile: Dockerfile.react
    container_name: react-app-container
    ports:
      - "5173:5173"
    networks:
      - my-network
    depends_on:
      - mysql
    volumes:
      - ./react-app:/react-app


volumes:
  mysql-data:

networks:
  my-network:
